version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat deploy

branches:
  only:
    - 1.5.0

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  fast_finish: true