on:
  pull_request:
    types: [opened]

jobs:
  copy-labels:
    runs-on: ubuntu-latest
    name: Copy labels from linked issues
    steps:
      - name: copy-labels
        uses: michalvankodev/copy-issue-labels@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels-to-include: |
            bug
            build-configuration
            breaking-change
            code-maintenance
            dependencies
            feature
            ignore-for-release-note
            performance
            refactor
            repo-admin
            translations
